version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: "host"
    depends_on:
      - redis
  redis:
    image: redis:3.2
    ports:
      - 6379:6379